# Olist E-Commerce Data Analysis
### End-to-End Data Analytics Project

**Dataset:** Brazilian E-Commerce Public Dataset by Olist  
**Tools:** Python, Pandas, NumPy, SQL and Power BI

**Project Workflow:**

Data Loading → Data Quality Checks → Data Cleaning → SQL Analysis → Power BI Dashboard

## 1. Importing Libraries

In [245]:
import pandas as pd
import numpy as np

## 2. Loading Datasets

In [246]:
folder = r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\raw"

In [247]:
customers = pd.read_csv(folder + "/olist_customers_dataset.csv")
geolocation = pd.read_csv(folder + "/olist_geolocation_dataset.csv")
order_items = pd.read_csv(folder + "/olist_order_items_dataset.csv")
order_payments = pd.read_csv(folder + "/olist_order_payments_dataset.csv")
order_reviews = pd.read_csv(folder + "/olist_order_reviews_dataset.csv")
orders = pd.read_csv(folder + "/olist_orders_dataset.csv")
products = pd.read_csv(folder + "/olist_products_dataset.csv")
sellers = pd.read_csv(folder + "/olist_sellers_dataset.csv")
category_translation = pd.read_csv(folder + "/product_category_name_translation.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

## 3. Initial Dataset Overview
### Understanding Dataset Structure

In [248]:
print("Customers:", customers.shape)
print("Geolocation:", geolocation.shape)
print("Order Items:", order_items.shape)
print("Order Payments:", order_payments.shape)
print("Order Reviews:", order_reviews.shape)
print("Orders:", orders.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Geolocation: (1000163, 5)
Order Items: (112650, 7)
Order Payments: (103886, 5)
Order Reviews: (99224, 7)
Orders: (99441, 8)
Products: (32951, 9)
Sellers: (3095, 4)
Category Translation: (71, 2)

In [249]:
print("Customers:", customers.dtypes)
print("Geolocation:", geolocation.dtypes)
print("Order Items:", order_items.dtypes)
print("Order Payments:", order_payments.dtypes)
print("Order Reviews:", order_reviews.dtypes)
print("Orders:", orders.dtypes)
print("Products:", products.dtypes)
print("Sellers:", sellers.dtypes)
print("Category Translation:", category_translation.dtypes)

Customers: customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
Geolocation: geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object
Order Items: order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object
Order Payments: order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object
Order Reviews: review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object
Orders: order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object
Products: product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
Sellers: seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object
Category Translation: product_category_name            object
product_category_name_english    object
dtype: object

In [250]:
for df_name, df in {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}.items():
    print("\n", df_name)
    print(df.isnull().sum())

 customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

 geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

 order_items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

 order_payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 order_reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

 products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

 sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 category_translation
product_category_name            0
product_category_name_english    0
dtype: int64

## 4. Customers Dataset — Data Cleaning & Quality Check

### 4.1 First Five Rows

In [251]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### 4.2 Data Types

In [252]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

### 4.3 Missing Values

In [253]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

### 4.4 Duplicate Rows

In [254]:
customers.duplicated().sum()

np.int64(0)

### 4.5 Duplicate Customer IDs

In [255]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [256]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

### 4.6 Data Cleaning & Transformation

In [257]:
customers_clean = customers.copy()

In [258]:
customers_clean["customer_zip_code_prefix"] = customers_clean["customer_zip_code_prefix"].astype(str)

In [259]:
customers_clean.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [260]:
customers_clean["customer_city"].unique()

array(['franca', 'sao bernardo do campo', 'sao paulo', ...,
       'monte bonito', 'sao rafael', 'eugenio de castro'],
      shape=(4119,), dtype=object)

In [261]:
customers_clean["customer_state"].unique()

array(['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA',
       'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB',
       'TO', 'PI', 'AC', 'SE', 'RR'], dtype=object)

In [262]:
customers_clean["customer_city"].nunique()

4119

In [263]:
customers_clean["customer_city"].str.normalize("NFKD").str.encode(
    "ascii", errors="ignore"
).str.decode("utf-8").nunique()

4119

In [264]:
customers_clean["customer_city"] = (
    customers_clean["customer_city"]
    .str.strip()
    .str.lower()
)

In [265]:
(customers_clean["customer_city"] != customers_clean["customer_city"].str.strip()).sum()

np.int64(0)

In [266]:
(customers_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 4.7 Save Cleaned Customers Dataset

In [267]:
customers_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_customers.csv", index=False)

print("Cleaned customers dataset saved successfully!")

Cleaned customers dataset saved successfully!

## 5. Geolocation Dataset — Data Cleaning & Quality Checks

### 5.1 First 5 Rows

In [268]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

### 5.2 Data Types

In [269]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

### 5.3 Missing Values

In [270]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

### 5.4 Duplicate Rows

In [271]:
geolocation.duplicated().sum()

np.int64(261831)

### 5.5 Data Cleaning & Transformation

In [272]:
geolocation_clean = geolocation.copy()

In [273]:
geolocation_clean["geolocation_zip_code_prefix"] = geolocation_clean["geolocation_zip_code_prefix"].astype(str)

In [274]:
geolocation_clean.dtypes

geolocation_zip_code_prefix     object
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [275]:
geolocation_clean["geolocation_city"].unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], shape=(8011,), dtype=object)

In [276]:
geolocation_clean["geolocation_state"].unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

In [277]:
geolocation_clean["geolocation_city"].nunique()

8011

In [278]:
geolocation_clean["geolocation_city"].str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8").nunique()

5968

In [279]:
geolocation_clean["geolocation_city"] = (
    geolocation_clean["geolocation_city"]
    .str.normalize("NFKD")
    .str.encode("ascii", errors="ignore")
    .str.decode("utf-8")
    .str.strip()
)

In [280]:
geolocation_clean["geolocation_city"].nunique()

5966

In [281]:
geolocation_clean["geolocation_city"].unique()

array(['sao paulo', 'sao bernardo do campo', 'jundiai', ...,
       'floriano peixoto', 'erebango', 'santa cecilia do sul'],
      shape=(5966,), dtype=object)

In [282]:
geolocation_clean[
    geolocation_clean["geolocation_city"].str.contains(
        r"[^\x00-\x7F]",
        regex=True,
        na=False
    )
]["geolocation_city"].unique()

array([], dtype=object)

In [283]:
geolocation_clean["geolocation_city"] = (
    geolocation_clean["geolocation_city"]
    .str.strip()
    .str.lower()
)

In [284]:
(geolocation_clean["geolocation_city"] != geolocation_clean["geolocation_city"].str.strip()).sum()

np.int64(0)

### 5.6 Investigating Duplicate Rows

In [285]:
geolocation_clean[geolocation_clean.duplicated()].head(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
72,1046,-23.545320,-46.644069,sao paulo,SP
79,1050,-23.549854,-46.643139,sao paulo,SP
80,1032,-23.540775,-46.635515,sao paulo,SP
82,1046,-23.546081,-46.644820,sao paulo,SP
86,1048,-23.547449,-46.640169,sao paulo,SP

In [286]:
geolocation_clean[geolocation_clean.duplicated(keep=False)].head(20)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP
10,1013,-23.547325,-46.634184,sao paulo,SP
13,1012,-23.548946,-46.634671,sao paulo,SP
14,1037,-23.545187,-46.637855,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
16,1039,-23.541883,-46.639919,sao paulo,SP
17,1024,-23.541390,-46.629899,sao paulo,SP
18,1009,-23.546935,-46.636588,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP
21,1020,-23.552235,-46.628441,sao paulo,SP
22,1011,-23.546690,-46.635447,sao paulo,SP
24,1050,-23.549774,-46.645599,sao paulo,SP
25,1045,-23.541594,-46.641894,sao paulo,SP

### 5.7 Remove Exact Duplicate Rows

In [287]:
geolocation_clean = geolocation_clean.drop_duplicates()

In [288]:
geolocation_clean.shape

(720494, 5)

In [289]:
geolocation_clean.duplicated().sum()

np.int64(0)

### 5.8 Save Cleaned Geolocation Dataset

In [290]:
geolocation_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_geolocation.csv", index=False)

print("Cleaned geolocation dataset saved successfully!")

Cleaned geolocation dataset saved successfully!

## 6. Order Items Dataset — Data Cleaning & Quality Checks

## 6.1 First 5 Rows

In [291]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

## 6.2 Data Types

In [292]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

## 6.3 Missing Values

In [293]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

## 6.4 Duplicate Rows

In [294]:
order_items.duplicated().sum()

np.int64(0)

### 6.5 Data Cleaning & Transformation

In [295]:
order_items_clean = order_items.copy()

In [296]:
order_items_clean["order_item_id"] = order_items_clean["order_item_id"].astype(str)

In [297]:
order_items_clean["shipping_limit_date"] = pd.to_datetime(order_items_clean["shipping_limit_date"])

In [298]:
order_items_clean.dtypes

order_id                       object
order_item_id                  object
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

### 6.6 Data Validation Check

In [299]:
order_items_clean[["price", "freight_value"]].min()

price            0.85
freight_value    0.00
dtype: float64

In [300]:
order_items_clean["shipping_limit_date"].loc[
    order_items_clean["shipping_limit_date"].notna()
].astype(str).str.match(
    r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$"
).value_counts()

shipping_limit_date
True    112650
Name: count, dtype: int64

In [301]:
(order_items_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 6.7 Save Cleaned Order Items Dataset

In [302]:
order_items_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_order_items.csv", index = False)
print("Cleaned order items dataset saved successfully!")

Cleaned order items dataset saved successfully!

## 7. Order Payments Dataset — Data Cleaning & Quality Checks

## 7.1 First Five Rows

In [303]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

### 7.2 Data Types

In [304]:
order_payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

### 7.3 Missing Values

In [305]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

### 7.4 Duplicate Rows

In [306]:
order_payments.duplicated().sum()

np.int64(0)

### 7.5 Data Validation Checks

In [307]:
order_payments["payment_value"].min()

0.0

In [308]:
order_payments["payment_installments"].min()

0

In [309]:
order_payments["payment_installments"].max()

24

In [310]:
order_payments["payment_installments"].value_counts().sort_index().head()

payment_installments
0        2
1    52546
2    12413
3    10461
4     7098
Name: count, dtype: int64

In [311]:
order_payments["payment_value"].eq(0).sum()

np.int64(9)

In [312]:
order_payments[order_payments["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [313]:
order_payments[order_payments["payment_value"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

### 7.6 Data Cleaning & Transformation

In [314]:
order_payments_clean = order_payments.copy()

In [315]:
order_payments_clean.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [316]:
order_payments_clean["payment_type"].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [317]:
order_payments_clean["payment_type"].nunique()

5

In [318]:
order_payments_clean["payment_type"].str.strip().nunique()

5

In [319]:
(order_payments_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 7.7 Save Cleaned Order Payments Dataset

In [320]:
order_payments_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_order_payments.csv", index = False)

print("Cleaned order payments dataset saved successfully!")

Cleaned order payments dataset saved successfully!

## 8. Order Reviews Dataset — Data Cleaning & Quality Checks

### 8.1 First 5 Rows

In [321]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

### 8.2 Data Types

In [322]:
order_reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

### 8.3 Missing Values

In [323]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

### 8.4 Duplicate Rows

In [324]:
order_reviews.duplicated().sum()

np.int64(0)

### 8.5 Data Type Correction

In [325]:
order_reviews_clean = order_reviews.copy()

In [326]:
order_reviews_clean["review_creation_date"] = pd.to_datetime(order_reviews_clean["review_creation_date"])
order_reviews_clean["review_answer_timestamp"] = pd.to_datetime(order_reviews_clean["review_answer_timestamp"])

In [327]:
order_reviews_clean[["review_creation_date", "review_answer_timestamp"]].dtypes

review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

### 8.6 Review Score Validation

In [328]:
order_reviews_clean["review_score"].min(), order_reviews_clean["review_score"].max()

(1, 5)

In [329]:
sorted(order_reviews_clean["review_score"].unique())

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

### 8.7 Missing Value Analysis

In [330]:
(order_reviews_clean.isnull().sum() / len(order_reviews_clean) * 100).round(2)

review_id                   0.00
order_id                    0.00
review_score                0.00
review_comment_title       88.34
review_comment_message     58.70
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

In [331]:
order_reviews_clean.loc[
    order_reviews_clean["review_comment_title"].notna(),
    "review_comment_title"
    ].head(10)

9                   recomendo
15            Super recomendo
19    Não chegou meu produto
22                      Ótimo
34                 Muito bom.
36                        Bom
38               Maravilhoso!
43           Entrega perfeita
53                      Ótimo
59                   MT lindo
Name: review_comment_title, dtype: object

In [332]:
order_reviews_clean.loc[
    order_reviews_clean["review_comment_message"].notna(),
    "review_comment_message"
].head(10)

3                 Recebi bem antes do prazo estipulado.
4     Parabéns lojas lannister adorei comprar pela I...
9     aparelho eficiente. no site a marca do aparelh...
12      Mas um pouco ,travando...pelo valor ta Boa.\r\n
15    Vendedor confiável, produto ok e entrega antes...
16    GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...
19                                              Péssimo
22                                         Loja nota 10
24                obrigado pela atençao amim dispensada
27    A compra foi realizada facilmente.\r\nA entreg...
Name: review_comment_message, dtype: object

### 8.8 Text & Categorical Consistency

In [333]:
(order_reviews_clean["review_comment_title"] == "").sum()

np.int64(0)

In [334]:
order_reviews_clean["review_comment_title"].str.strip().eq("").sum()

np.int64(2)

In [335]:
(order_reviews_clean["review_comment_message"] == "").sum()

np.int64(0)

In [336]:
order_reviews_clean["review_comment_message"].str.strip().eq("").sum()

np.int64(27)

### 8.9 Handling Empty / Whitespace-Only Values

In [337]:
order_reviews_clean["review_comment_title"] = (
    order_reviews_clean["review_comment_title"]
    .replace(r"^\s*$", np.nan, regex=True)
)

In [338]:
order_reviews_clean["review_comment_message"] = (
    order_reviews_clean["review_comment_message"]
    .replace(r"^\s*$", np.nan, regex=True)
)

In [339]:
(order_reviews_clean.isnull().sum() / len(order_reviews_clean) * 100).round(2)

review_id                   0.00
order_id                    0.00
review_score                0.00
review_comment_title       88.34
review_comment_message     58.73
review_creation_date        0.00
review_answer_timestamp     0.00
dtype: float64

### 8.10 Final Date Validation

In [340]:
order_reviews_clean[[
    "review_creation_date",
    "review_answer_timestamp"
]].agg(["min", "max"])

    review_creation_date review_answer_timestamp
min           2016-10-02     2016-10-07 18:32:28
max           2018-08-31     2018-10-29 12:27:35

In [341]:
order_reviews_clean[["review_creation_date", "review_answer_timestamp"]].apply(
    lambda x: x[x.notna()].astype(str).str.match(
        r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$"
    ).value_counts()
)

      review_creation_date  review_answer_timestamp
True                 99224                    99224

In [342]:
(order_reviews_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 8.11 Save Clean Dataset

In [343]:
order_reviews_clean.to_csv( r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_order_reviews.csv", index = False)

print("Cleaned order reviews dataset saved successfully!")

Cleaned order reviews dataset saved successfully!

## 9. Orders Dataset - Data Cleaning and Quality Check

### 9.1 First Five Rows

In [344]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

### 9.2 Data Types

In [345]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

### 9.3 Missing Values

In [346]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### 9.4 Duplicate Rows

In [347]:
orders.duplicated().sum()

np.int64(0)

### 9.5 Data Type Correction

In [348]:
orders_clean = orders.copy()

In [349]:
orders_clean["order_purchase_timestamp"] = pd.to_datetime(
    orders_clean["order_purchase_timestamp"]
)

orders_clean["order_approved_at"] = pd.to_datetime(
    orders_clean["order_approved_at"]
)

orders_clean["order_delivered_carrier_date"] = pd.to_datetime(
    orders_clean["order_delivered_carrier_date"]
)

orders_clean["order_delivered_customer_date"] = pd.to_datetime(
    orders_clean["order_delivered_customer_date"]
)

orders_clean["order_estimated_delivery_date"] = pd.to_datetime(
    orders_clean["order_estimated_delivery_date"]
)

In [350]:
orders_clean.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [351]:
orders_clean[[
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]].apply(
    lambda x: x[x.notna()].astype(str).str.match(
        r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$"
    ).value_counts()
)

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
False,NaN,NaN,NaN,NaN,99441.0
True,99441.0,99281.0,97658.0,96476.0,NaN

In [352]:
orders_clean.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23

In [353]:
orders_clean["order_estimated_delivery_date"].loc[
    orders_clean["order_estimated_delivery_date"].notna()
].astype(str).str.match(
    r"^\d{4}-\d{2}-\d{2}$"
).value_counts()

order_estimated_delivery_date
True    99441
Name: count, dtype: int64

### 9.6 Order Status – Categorical Consistency Check

In [354]:
orders_clean["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [355]:
orders_clean["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [356]:
(orders_clean["order_status"] != orders_clean["order_status"].str.strip()).sum()

np.int64(0)

In [357]:
(orders_clean["order_status"] == orders_clean["order_status"].str.lower()).all()

np.True_

### 9.7 Missing Value Analysis

In [358]:
(orders_clean.isnull().sum() / len(orders_clean) * 100).round(2)

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

In [359]:
orders_clean[orders_clean["order_approved_at"].isna()]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [360]:
(orders_clean["order_approved_at"].astype(str).str.strip() == "").sum()

np.int64(0)

In [361]:
orders_clean[orders_clean["order_delivered_carrier_date"].isna()]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [362]:
(orders_clean["order_delivered_carrier_date"].astype(str).str.strip() == "").sum()

np.int64(0)

In [363]:
orders_clean[orders_clean["order_delivered_customer_date"].isna()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [364]:
(orders_clean["order_delivered_customer_date"].astype(str).str.strip() == "").sum()

np.int64(0)

### 9.8 Data Validation

In [365]:
(orders_clean["order_approved_at"] < orders_clean["order_purchase_timestamp"]).sum()

np.int64(0)

In [366]:
(orders_clean["order_delivered_carrier_date"] < orders_clean["order_purchase_timestamp"]).sum()

np.int64(166)

In [367]:
(orders_clean["order_delivered_customer_date"] < orders_clean["order_purchase_timestamp"]).sum()

np.int64(0)

In [368]:
(orders_clean["order_delivered_customer_date"] < orders_clean["order_delivered_carrier_date"]).sum()

np.int64(23)

In [369]:
orders_clean[
    orders_clean["order_delivered_carrier_date"] <
    orders_clean["order_purchase_timestamp"]
][[
    "order_id",
    "order_status",
    "order_purchase_timestamp",
    "order_delivered_carrier_date"
]].head(20)

,order_id,order_status,order_purchase_timestamp,order_delivered_carrier_date
615,b9afddbdcfadc9a87b41a83271c3e888,delivered,2018-08-16 13:50:48,2018-08-16 13:27:00
1111,ad133696906f6a78826daa0911b7daec,delivered,2018-06-15 15:41:22,2018-06-15 14:52:00
1329,74e033208dc13a7b8127eb8e73d09b76,delivered,2018-05-02 10:48:44,2018-05-02 09:49:00
1372,a6b58794fd2ba533359a76c08df576e3,delivered,2018-05-14 15:18:23,2018-05-14 13:46:00
1864,5792e0b1c8c8a2bf53af468c9a422c88,delivered,2018-07-26 13:25:14,2018-07-26 12:42:00
2760,c3eb293fd154223498b6551a728203e8,delivered,2018-07-19 14:06:04,2018-07-19 13:49:00
3473,b0c2a7d04b165525254254a728c50a4e,delivered,2018-06-07 13:28:30,2018-06-07 13:22:00
3661,2033a4586b5bec3229ebc1675a8ae092,delivered,2018-06-12 10:10:25,2018-06-12 10:09:00
4114,08adcddad19d3acf37d1fa01cb9ded1e,delivered,2018-06-27 11:16:44,2018-06-27 10:57:00
4159,dee6298ce7d1fb2645141ef9972157aa,shipped,2018-04-30 14:06:12,2018-04-30 12:59:00
4256,4e157a36ea9cf89bde6fff57a780b525,delivered,2018-08-24 14:37:50,2018-08-24 12:43:00
4660,d454d6650d375ebc3f9667a4d2fe161c,delivered,2018-05-10 09:12:16,2018-05-10 09:11:00
5214,a5a9f45d795fafe0077043697f62fd4f,delivered,2018-07-04 14:45:20,2018-07-04 13:41:00
5889,dab23a46abb860b6b4816df41eacd610,delivered,2018-08-08 15:42:27,2018-08-08 14:56:00
6014,b4180badf3ac49892e23d6e0276f1e84,delivered,2018-04-26 14:44:05,2018-04-26 13:51:00
8126,6c5d1e03493316b72304f07834a03325,delivered,2018-06-12 13:56:41,2018-06-12 13:06:00
9649,ede6a833580744e002b0ee65323a3006,delivered,2018-08-17 15:11:53,2018-08-17 14:07:00
9679,1227f9af3b2ddb0b95060aab8e5b3dc7,delivered,2018-05-10 14:48:29,2018-05-10 14:00:00
10047,2996234f359b5a3b99263b0f5b841d86,delivered,2018-08-15 15:48:50,2018-08-15 14:16:00
10584,108c3238d247dead3fd7423cf8990c5b,delivered,2018-08-14 13:49:12,2018-08-14 13:17:00

In [370]:
orders_clean[
    orders_clean["order_delivered_customer_date"] <
    orders_clean["order_delivered_carrier_date"]
][[
    "order_id",
    "order_status",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]].head(20)

,order_id,order_status,order_delivered_carrier_date,order_delivered_customer_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,delivered,2017-07-28 16:57:58,2017-07-25 19:32:56
9553,383aa8b2724fe452d9ccd9934a8c628b,delivered,2017-07-07 17:22:41,2017-07-06 14:27:51
13487,cb1134f9010d242e9515ad1c78ec0c39,delivered,2017-07-20 19:22:02,2017-07-19 14:13:28
14474,dceb62e8fa94b46006c9554fed743df0,delivered,2017-08-01 18:23:30,2017-07-26 18:09:10
19268,5f9d46795c3126674e52becb3a1a517f,delivered,2017-07-20 23:03:42,2017-07-20 18:52:41
21338,8c78d01de3a9009e23d6877a7cc9be20,delivered,2016-10-26 11:41:53,2016-10-25 17:51:46
22520,b27af682321527a6349f1761eb3f360c,delivered,2017-06-27 14:51:54,2017-06-26 15:45:35
25393,1cc3ae63caffff2d6c3ee3e78e074acf,delivered,2017-08-10 18:28:56,2017-08-10 18:05:38
25646,e37f11cae9985ca58f0b56f268720537,delivered,2017-08-01 18:17:47,2017-07-31 17:49:56
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,delivered,2017-08-09 18:18:43,2017-08-01 21:13:01
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,delivered,2017-03-02 17:34:26,2017-02-14 15:15:57
41636,b866af202be0692766081310cd4085e1,delivered,2017-02-20 02:32:08,2017-02-15 03:53:46
45302,29941903985f944b0ffc49c479c1547d,delivered,2017-06-09 15:07:29,2017-06-02 11:09:16
49933,76458889992169d3135b264dc13aec67,delivered,2016-10-26 11:43:06,2016-10-20 18:03:17
50373,0922ee1619de7b995648e5a8407afb91,delivered,2017-07-14 12:41:34,2017-07-12 20:49:42
58428,fbffbaaa30f4077e87ec6acdb835b278,delivered,2017-08-04 20:04:17,2017-08-03 20:30:00
68312,3ee6694bb99d5a6db0deceffcd099597,delivered,2017-07-11 18:15:40,2017-07-11 17:41:26
71227,19feb5627c41ea1b36a8e50a469b3644,delivered,2016-10-26 11:42:05,2016-10-20 19:07:54
74967,d5558a097766363b8e76b38c43332e8a,delivered,2017-02-15 08:55:26,2017-02-10 07:58:32
76120,771c4f1f521f462e4b95619e648aaeab,delivered,2017-03-30 13:14:34,2017-03-28 17:28:32

In [371]:
invalid_carrier = (
    orders_clean["order_delivered_carrier_date"] <
    orders_clean["order_purchase_timestamp"]
)

invalid_carrier.sum()

np.int64(166)

In [372]:
(invalid_carrier.sum() / len(orders_clean) * 100).round(2)

np.float64(0.17)

In [373]:
orders_clean = orders_clean[~invalid_carrier]

In [374]:
orders_clean.shape

(99275, 8)

In [375]:
invalid_customer_delivery = (
    orders_clean["order_delivered_customer_date"] <
    orders_clean["order_delivered_carrier_date"]
)

invalid_customer_delivery.sum()

np.int64(23)

In [376]:
(invalid_customer_delivery.sum() / len(orders_clean) * 100).round(2)

np.float64(0.02)

In [377]:
orders_clean = orders_clean[~invalid_customer_delivery]

In [378]:
orders_clean.shape

(99252, 8)

### 9.9 Final Verification

In [379]:
orders_clean.shape

(99252, 8)

In [380]:
orders_clean.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2964
order_estimated_delivery_date       0
dtype: int64

In [381]:
orders_clean.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [382]:
orders_clean["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [383]:
(
    orders_clean["order_delivered_carrier_date"] <
    orders_clean["order_purchase_timestamp"]
).sum()

np.int64(0)

In [384]:
(
    orders_clean["order_delivered_customer_date"] <
    orders_clean["order_delivered_carrier_date"]
).sum()

np.int64(0)

In [385]:
(orders_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 9.10 Save Cleaned Orders Dataset

In [386]:
orders_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_orders.csv", index=False)

print("Cleaned orders dataset saved successfully!")

Cleaned orders dataset saved successfully!

## 10. Products — Data Cleaning & Quality Check

### 10.1 First 5 Rows

In [387]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

### 10.2 Data Types

In [388]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

### 10.3 Missing Values

In [389]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

### 10.4 Duplicate Rows

In [390]:
products.duplicated().sum()

np.int64(0)

### 10.5 Data Type Validation & Correction

In [391]:
products_clean = products.copy()

In [392]:
products_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
product_name_lenght,32341.0,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

In [393]:
products_clean["product_category_name"].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

### 10.6 Product Category — Consistency Check

In [394]:
products_clean["product_category_name"].nunique()

73

In [395]:
products_clean["product_category_name"].str.strip().str.lower().str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8").nunique()

73

### 10.7 Missing Value Analysis

In [396]:
missing_percentage = (products_clean.isnull().sum() / len(products_clean)) * 100

missing_percentage.round(2)

product_id                    0.00
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

### 10.7 Empty string & whitespace check

In [397]:
products_clean["product_category_name"].eq("").sum()

np.int64(0)

In [398]:
products_clean["product_category_name"].str.strip().eq("").sum()

np.int64(0)

In [399]:
products_clean.astype("string").apply(lambda x: x.str.strip().eq("").sum())

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

### 10.9 Missing Value Investigation

In [400]:
products_clean[products_clean.isnull().any(axis=1)].head(20)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0
436,3a78f64aac654298e4b9aff32fc21818,NaN,NaN,NaN,NaN,4300.0,30.0,10.0,48.0
459,bcb815bba008d89458e428078c0b9211,NaN,NaN,NaN,NaN,150.0,16.0,2.0,11.0
504,6b82874c6b51b92913dcdb364eaaae0f,NaN,NaN,NaN,NaN,21450.0,70.0,34.0,50.0
514,c68b419d9c6038271b85bac98adb0fc9,NaN,NaN,NaN,NaN,1000.0,16.0,14.0,30.0
552,1dcd65bb5dd967d7b4c6b0223cefb838,NaN,NaN,NaN,NaN,9150.0,33.0,30.0,44.0
616,671446e8e3aa3df1eca47b6c354a2921,NaN,NaN,NaN,NaN,5500.0,33.0,22.0,33.0
627,f0ea71b6e2ab4cb3bd8f5ba522a25a56,NaN,NaN,NaN,NaN,1300.0,30.0,20.0,30.0
628,fedccbd5e370e8ddb7aae6fb4cb70347,NaN,NaN,NaN,NaN,1200.0,20.0,20.0,20.0
696,212cc0fa7359ab242a697a03a574f719,NaN,NaN,NaN,NaN,200.0,16.0,2.0,11.0
700,6b7879a37ac2dbe5289a16706e859870,NaN,NaN,NaN,NaN,950.0,45.0,12.0,30.0

In [401]:
products_clean[
    products_clean[["product_weight_g", "product_length_cm",
                    "product_height_cm", "product_width_cm"]].isnull().any(axis=1)
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 10.8 Percentage of Rows with Missing Physical Measurements

In [402]:
missing_physical = products_clean[
    products_clean[["product_weight_g", "product_length_cm",
                    "product_height_cm", "product_width_cm"]].isnull().any(axis=1)
]

round((missing_physical.shape[0] / products_clean.shape[0]) * 100, 2)

0.01

### 10.9 Remove Rows with Missing Physical Measurements

In [403]:
products_clean = products_clean.dropna(
    subset=["product_weight_g", "product_length_cm",
            "product_height_cm", "product_width_cm"]
)

In [404]:
products_clean.shape

(32949, 9)

In [405]:
products_clean[
    ["product_weight_g", "product_length_cm",
     "product_height_cm", "product_width_cm"]
].isnull().sum()

product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

### 10.10 Final Missing Value Check

In [406]:
products_clean.isnull().sum()

product_id                      0
product_category_name         609
product_name_lenght           609
product_description_lenght    609
product_photos_qty            609
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

### 10.10 Data Consistency Check

In [407]:
products_clean.loc[
    products_clean["product_category_name"].notna() &
    (products_clean["product_category_name"].str.strip() != products_clean["product_category_name"]),
    "product_category_name"
].unique()

array([], dtype=object)

In [408]:
products_clean.duplicated().sum()

np.int64(0)

In [409]:
products_clean.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [410]:
(products_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 10.11 Save Cleaned Products Dataset

In [411]:
products_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_products.csv", index=False)

print("Cleaned products dataset saved successfully!")

Cleaned products dataset saved successfully!

## 1. Seller Dataset — Data Cleaning & Quality Check

### 11.1 First 5 Rows

In [412]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### 11.2 Data Types

In [413]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

### 11.3 Missing Values

In [414]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

### 11.4 Duplicate Rows

In [415]:
sellers.duplicated().sum()

np.int64(0)

### 11.5 Data Type Correction

In [416]:
sellers_clean = sellers.copy()

In [417]:
sellers_clean["seller_zip_code_prefix"] = sellers_clean["seller_zip_code_prefix"].astype("object")

In [418]:
sellers_clean.dtypes

seller_id                 object
seller_zip_code_prefix    object
seller_city               object
seller_state              object
dtype: object

In [419]:
sellers_clean["seller_city"].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balenario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'ferraz de  vasconcelos', 'mirandopolis', 'bauru', 'jacarei',
       'itu', 'laranjeiras do sul', 'videira', 'florianopolis',
       'itapecerica da serra', 'mamanguape', 'ponte nova', 'goioere',
       'pederneiras', 'itapevi', 'goiania', 'campina grande',
       'estancia velha', 'resende', 'maua', 'caratinga', 'auriflama/sp',
       'cafelandia', 'uba', 'sao paulo / sao paulo',
       'sao jose do rio preto', 'porto ferreira', 'tres coroas',
       'blumenau', 'mogi das cruzes', 'jaci', 'laranjal paulista',
       'americana', 'sertanopolis', 'apucarana', 'colombo',
       'vicente de carvalho', 'mesquita', 'sao pauo', 'cascavel',
       'fazenda rio grande', 'taboao da serra', 'sao jose dos campos',
       'toledo', 'marechal candido rondon', 'jundiai', 'mandirituba',
       'suzano', 'vespasiano', 'santa rosa', 'sao joaquim da barra',
       'santo antonio de posse', 'uruguaiana', 'campanha', 'piracanjuba',
       'concordia', 'santa rita do sapucai', 'barretos', 'indaiatuba',
       'nilopolis', 'pompeia', 'barro alto', 'são paulo', 'praia grande',
       'luiz alves', 'brusque', 'criciuma', 'jales', 'atibaia',
       'rio branco', 'barra mansa', 'marilia', 'bahia', 'taubate',
       'cascavael', 'monteiro lobato', 'viana', 'paraiba do sul',
       'mococa', 'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'sao  jose dos pinhais', 'boituva',
       'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica / es', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'mogi das cruses', 'hortolandia',
       'ipatinga', 'laguna', 'dores de campos', 'sao paulo - sp',
       'araras', 'divisa nova', 'igaracu do tiete', 'pitangueiras',
       'campo grande', 'garca', 'presidente epitacio', 'sbc/sp',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'santo andre/sao paulo', 'ipe', 'messias targino',
       'varginha', 'botucatu', 'domingos martins', 'uberaba',
       'coronel fabriciano', 'cachoeirinha', 's jose do rio preto',
       'taruma', 'pirassununga', 'aruja', 'sp / sp', 'angra dos reis',
       'juzeiro do norte', 'laurentino', 'flores da cunha', 'montenegro',
       'pedregulho', 'novo hamburgo', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'cariacica',
       'monte alegre do sul', 'sp', 'lagoa da prata', 'rolante',
       'teresopolis', 'itaporanga', 'campo largo', 'sao joao de meriti',
       'maua/sao paulo', 'bom jesus dos perdoes', 'brotas', 'irece',
       'coxim', 'jau', 'conselheiro lafaiete', 'amparo',
       'sao miguel do oeste', 'gaspar', 'rio bonito', 'mandaguari',
       'vargem grande paulista', 'conchal', 'cambe', 'marialva',
       'alfenas', 'balneario camboriu', 'palhoca', 'sao bernardo do capo',
       'guara', 'colatina', 'franco da rocha', 'lambari',
       'mogi das cruzes / sp', 'treze tilias',
       'rio de janeiro \\rio de janeiro', 'paulo lopes', 'santa cecilia',
       'braco do norte', 'floresta', 'farroupilha', 'castro', 'luziania',
       'joao monlevade', 'pelotas', 'sao bento', 'campos dos goytacazes',
       'ouro fino', 'sao jose dos pinhas', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena/ minas gerais', 'vera cruz', 'parnamirim',
       'santo angelo', 'paincandu', 'tres rios', 'tanabi',
       'portoferreira', 'itatiba', 'sarandi', 'cravinhos', 'morrinhos',
       'bebedouro', 'almirante tamandare', 'bertioga', 'natal',
       'belo horizont', 'ivoti', 'andira-pr', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'sao paulo sp',
       'rio de janeiro / rio de janeiro', 'andradas', 'sando andre',
       'nova odessa', 'paulinia', 'extrema', 'olimpia',
       'angra dos reis rj', 'ronda alta', 'sao  paulo', 'sao vicente',
       'pinhais/pr', 'portao', 'registro', 'ao bernardo do campo',
       'carmo do cajuru', 'embu das artes', 'fernando prestes',
       'castro pires', 'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'barbacena',
       'caieiras', 'buritama', 'erechim', 'itapetininga', 'pinhalzinho',
       'descalvado', 'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'garulhos', 'jarinu', 'nova petropolis',
       'ribeirao preto / sao paulo', 'camboriu', 'nova trento',
       'sao luis', 'sao jose do rio pret', 'eusebio', 'itaipulandia',
       'ipira', 'campo magro', 'tiradentes', 'sao paluo', 'baependi',
       'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases',
       'bariri', 'abadia de goias', 'alambari', 'ji parana', 'vassouras',
       'lorena', 'rodeio', 'louveira', 'guanhaes',
       'santo antonio de padua', 'presidente getulio', 'campos novos',
       'eunapolis', 'engenheiro coelho', 'rio das pedras',
       'afonso claudio', 'carapicuiba / sao paulo', 'centro', 'parana',
       'indaial', 'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao',
       'macatuba', 'sao joao da boa vista', 'teixeira soares',
       'mandaguacu', 'rio do oeste', 'vendas@creditparts.com.br',
       'armacao dos buzios', 'mateus leme', 'sao paulop',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'minas gerais', 'avare', 'ibirite',
       'santa maria da serra', 'auriflama', 'condor', 'ibia', 'guanambi',
       'caucaia', 'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'ribeirao pretp',
       'cianorte', 'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama/sp', 'dracena', 'ourinhos',
       'robeirao preto', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'rio de janeiro, rio de janeiro, brasil',
       'pouso alegre', 'timoteo', 'muqui', 'ipua', 'jacarei / sao paulo',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'riberao preto', 'aparecida de goiania', 'bandeirantes',
       'vitoria de santo antao', 'palotina', 'leme'], dtype=object)

### 11.6 Check Accent Consistency

In [420]:
sellers_clean["seller_city"].str.normalize("NFKD").str.encode(
    "ascii", errors="ignore"
).str.decode("utf-8").nunique()

609

In [421]:
sellers_clean["seller_city"].nunique()

611

In [422]:
sellers_clean.loc[
    sellers_clean["seller_city"].str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8")
    != sellers_clean["seller_city"],
    "seller_city"
].unique()

array(['são paulo', 'santa barbara d´oeste'], dtype=object)

In [423]:
sellers_clean["seller_city"] = sellers_clean["seller_city"].str.normalize("NFKD").str.encode(
    "ascii", errors="ignore"
).str.decode("utf-8")

In [424]:
sellers_clean["seller_city"].nunique()

609

In [425]:
sellers_clean.loc[
    sellers_clean["seller_city"].str.strip() != sellers_clean["seller_city"],
    "seller_city"
].count()

np.int64(0)

In [426]:
sellers_clean["seller_city"].str.count(r"\s{2,}").sum()

np.int64(3)

In [427]:
sellers_clean["seller_city"] = sellers_clean["seller_city"].str.replace(r"\s+", " ", regex=True)

In [428]:
sellers_clean["seller_city"].str.count(r"\s{2,}").sum()

np.int64(0)

In [429]:
sellers_clean["seller_city"].str.lower().eq(
    sellers_clean["seller_city"]
).all()

np.True_

In [430]:
sellers_clean.loc[
    sellers_clean["seller_city"].str.contains(r"[@()/]", regex=True),
    "seller_city"
].value_counts()

seller_city
auriflama/sp                       1
barbacena/ minas gerais            1
sao sebastiao da grama/sp          1
vendas@creditparts.com.br          1
carapicuiba / sao paulo            1
ribeirao preto / sao paulo         1
pinhais/pr                         1
rio de janeiro / rio de janeiro    1
mogi das cruzes / sp               1
sao paulo / sao paulo              1
maua/sao paulo                     1
sp / sp                            1
santo andre/sao paulo              1
arraial d'ajuda (porto seguro)     1
sbc/sp                             1
cariacica / es                     1
jacarei / sao paulo                1
Name: count, dtype: int64

In [431]:
sellers_clean["seller_city"] = sellers_clean["seller_city"].str.split("/").str[0].str.strip()

In [432]:
sellers_clean.loc[
    sellers_clean["seller_city"].isin(["sp", "vendas@creditparts.com.br"]),
    "seller_city"
] = pd.NA

In [433]:
sellers_clean["seller_city"].value_counts().tail(30)

seller_city
santa terezinha de goias     1
domingos martins             1
arvorezinha                  1
guiricema                    1
messias targino              1
ipe                          1
muriae                       1
cruzeiro                     1
aracaju                      1
joao pinheiro                1
barra velha                  1
sinop                        1
marialva                     1
santo antonio da patrulha    1
vargem grande paulista       1
mandaguari                   1
sao miguel do oeste          1
lages - sc                   1
coxim                        1
irece                        1
brotas                       1
bom jesus dos perdoes        1
itaporanga                   1
rolante                      1
monte alegre do sul          1
itaborai                     1
lagoa santa                  1
nhandeara                    1
guarapuava                   1
leme                         1
Name: count, dtype: int64

In [434]:
sellers_clean["seller_city"].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balenario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'mirandopolis', 'bauru', 'jacarei', 'itu', 'laranjeiras do sul',
       'videira', 'florianopolis', 'itapecerica da serra', 'mamanguape',
       'ponte nova', 'goioere', 'pederneiras', 'itapevi', 'goiania',
       'campina grande', 'estancia velha', 'resende', 'maua', 'caratinga',
       'auriflama', 'cafelandia', 'uba', 'sao jose do rio preto',
       'porto ferreira', 'tres coroas', 'blumenau', 'mogi das cruzes',
       'jaci', 'laranjal paulista', 'americana', 'sertanopolis',
       'apucarana', 'colombo', 'vicente de carvalho', 'mesquita',
       'sao pauo', 'cascavel', 'fazenda rio grande', 'taboao da serra',
       'sao jose dos campos', 'toledo', 'marechal candido rondon',
       'jundiai', 'mandirituba', 'suzano', 'vespasiano', 'santa rosa',
       'sao joaquim da barra', 'santo antonio de posse', 'uruguaiana',
       'campanha', 'piracanjuba', 'concordia', 'santa rita do sapucai',
       'barretos', 'indaiatuba', 'nilopolis', 'pompeia', 'barro alto',
       'praia grande', 'luiz alves', 'brusque', 'criciuma', 'jales',
       'atibaia', 'rio branco', 'barra mansa', 'marilia', 'bahia',
       'taubate', 'cascavael', 'monteiro lobato', 'viana',
       'paraiba do sul', 'mococa', 'sao roque', 'passos',
       'francisco beltrao', 'tocantins', 'porto belo', 'nova iguacu',
       'icara', 'lajeado', 'horizontina', 'votorantim', 'campo bom',
       'monte alto', 'fernandopolis', 'pedreira', 'poa', 'divinopolis',
       'santa barbara d oeste', 'canoas', 'mombuca', 'sete lagoas',
       'campo do meio', 'cordeiropolis', 'uberlandia', 'volta redonda',
       '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'boituva', 'mairipora', 'guaimbe',
       'parai', 'aperibe', 'jaguaruna', 'vila velha', 'juiz de fora',
       'fronteira', 'novo horizonte', 'pilar do sul', 'itajobi',
       'cariacica', 'prados', 'mucambo', 'montes claros', 'vicosa',
       'porto velho', 'sao jose do rio pardo', 'pato branco',
       'sao joao del rei', 'presidente prudente', 'paracambi',
       'serra negra', 'sao caetano do sul', 'bom jardim', 'serra redonda',
       'sao francisco do sul', 'betim', 'imbituva', 'guaratuba',
       'teresina', "sao miguel d'oeste", 'california', 'japira',
       'foz do iguacu', 'nova friburgo', 'itau de minas', 'oliveira',
       'sabara', 'pedrinhas paulista', 'votuporanga', 'holambra',
       'ararangua', 'pinhais', 'pato bragado', 'carazinho', 'arinos',
       'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'mogi das cruses', 'hortolandia',
       'ipatinga', 'laguna', 'dores de campos', 'sao paulo - sp',
       'araras', 'divisa nova', 'igaracu do tiete', 'pitangueiras',
       'campo grande', 'garca', 'presidente epitacio', 'sbc',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'ipe', 'messias targino', 'varginha', 'botucatu',
       'domingos martins', 'uberaba', 'coronel fabriciano',
       'cachoeirinha', 's jose do rio preto', 'taruma', 'pirassununga',
       'aruja', <NA>, 'angra dos reis', 'juzeiro do norte', 'laurentino',
       'flores da cunha', 'montenegro', 'pedregulho', 'novo hamburgo',
       'torres', 'aracaju', 'santa catarina', 'joao pinheiro',
       'bady bassitt', 'sinop', 'guarapuava', 'araucaria', 'vitoria',
       'batatais', 'lagoa santa', 'chapeco', 'umuarama', 'belford roxo',
       'monte alegre do sul', 'lagoa da prata', 'rolante', 'teresopolis',
       'itaporanga', 'campo largo', 'sao joao de meriti',
       'bom jesus dos perdoes', 'brotas', 'irece', 'coxim', 'jau',
       'conselheiro lafaiete', 'amparo', 'sao miguel do oeste', 'gaspar',
       'rio bonito', 'mandaguari', 'vargem grande paulista', 'conchal',
       'cambe', 'marialva', 'alfenas', 'balneario camboriu', 'palhoca',
       'sao bernardo do capo', 'guara', 'colatina', 'franco da rocha',
       'lambari', 'treze tilias', 'rio de janeiro \\rio de janeiro',
       'paulo lopes', 'santa cecilia', 'braco do norte', 'floresta',
       'farroupilha', 'castro', 'luziania', 'joao monlevade', 'pelotas',
       'sao bento', 'campos dos goytacazes', 'ouro fino',
       'sao jose dos pinhas', 'tiete', 'viamao', 'janauba', 'capivari',
       'santa terezinha de itaipu', 'igrejinha', 'sao bento do sul',
       'duque de caxias', 'araxa', 'canoinhas', 'recife', 'barbacena',
       'vera cruz', 'parnamirim', 'santo angelo', 'paincandu',
       'tres rios', 'tanabi', 'portoferreira', 'itatiba', 'sarandi',
       'cravinhos', 'morrinhos', 'bebedouro', 'almirante tamandare',
       'bertioga', 'natal', 'belo horizont', 'ivoti', 'andira-pr',
       'cerqueira cesar', 'marapoama', 'imigrante', 'mairinque',
       'sao paulo sp', 'andradas', 'sando andre', 'nova odessa',
       'paulinia', 'extrema', 'olimpia', 'angra dos reis rj',
       'ronda alta', 'sao vicente', 'portao', 'registro',
       'ao bernardo do campo', 'carmo do cajuru', 'embu das artes',
       'fernando prestes', 'castro pires', 'vargem grande do sul',
       'campina das missoes', 'sao pedro da aldeia', 'miguelopolis',
       'itapui', 'neopolis', 'mineiros do tiete', 'varzea paulista',
       'nova lima', 'caieiras', 'buritama', 'erechim', 'itapetininga',
       'pinhalzinho', 'descalvado', 'pitanga', 'bage', 'taio',
       "santa barbara d'oeste", 'patos de minas', 'garulhos', 'jarinu',
       'nova petropolis', 'camboriu', 'nova trento', 'sao luis',
       'sao jose do rio pret', 'eusebio', 'itaipulandia', 'ipira',
       'campo magro', 'tiradentes', 'sao paluo', 'baependi', 'embu guacu',
       'paraiso do sul', 'aparecida', 'cataguases', 'bariri',
       'abadia de goias', 'alambari', 'ji parana', 'vassouras', 'lorena',
       'rodeio', 'louveira', 'guanhaes', 'santo antonio de padua',
       'presidente getulio', 'campos novos', 'eunapolis',
       'engenheiro coelho', 'rio das pedras', 'afonso claudio', 'centro',
       'parana', 'indaial', 'bombinhas', 'orlandia', 'itapeva',
       'sao sebastiao', 'macatuba', 'sao joao da boa vista',
       'teixeira soares', 'mandaguacu', 'rio do oeste',
       'armacao dos buzios', 'mateus leme', 'sao paulop',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'minas gerais', 'avare', 'ibirite',
       'santa maria da serra', 'condor', 'ibia', 'guanambi', 'caucaia',
       'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'ribeirao pretp',
       'cianorte', 'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama', 'dracena', 'ourinhos', 'robeirao preto',
       'cacador', 'gama', 'queimados', 'cananeia', 'presidente bernardes',
       'pinhalao', 'sombrio', 'campo mourao', 'ilicinea', 'itabira',
       'barrinha', 'jussara', 'uniao da vitoria', 'triunfo',
       'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'rio de janeiro, rio de janeiro, brasil',
       'pouso alegre', 'timoteo', 'muqui', 'ipua', 'varzea alegre',
       'guaratingueta', 'tambau', 'irati', 'riberao preto',
       'aparecida de goiania', 'bandeirantes', 'vitoria de santo antao',
       'palotina', 'leme'], dtype=object)

In [435]:
city_corrections = {
    "sao pauo": "sao paulo",
    "cascavael": "cascavel",
    "floranopolis": "florianopolis",
    "mogi das cruses": "mogi das cruzes",
    "sao jose dos pinhas": "sao jose dos pinhais",
    "sao jose do rio pret": "sao jose do rio preto",
    "s jose do rio preto": "sao jose do rio preto",
    "juzeiro do norte": "juazeiro do norte",
    "belo horizont": "belo horizonte",
    "sao bernardo do capo": "sao bernardo do campo",
    "sando andre": "santo andre",
    "ao bernardo do campo": "sao bernardo do campo",
    "garulhos": "guarulhos",
    "sao paluo": "sao paulo",
    "sao paulop": "sao paulo",
    "sao jose dos pinhas": "sao jose dos pinhais",
    "ribeirao pretp": "ribeirao preto",
    "robeirao preto": "ribeirao preto",
    "riberao preto": "ribeirao preto",
    "scao jose do rio pardo": "sao jose do rio pardo",
    "balenario camboriu": "balneario camboriu",
    "paincandu": "paicandu",
    "portoferreira": "porto ferreira"
}

In [436]:
sellers_clean["seller_city"] = sellers_clean["seller_city"].replace(city_corrections)

In [437]:
sellers_clean.loc[
    sellers_clean["seller_city"].isin(
        ["04482255", "bahia", "santa catarina", "minas gerais", "parana"]
    ),
    "seller_city"
] = pd.NA

In [438]:
sellers_clean["seller_city"].isin(
    ["04482255", "bahia", "santa catarina", "minas gerais", "parana"]
).sum()

np.int64(0)

In [439]:
sellers_clean[sellers_clean["seller_city"].isin([
    "lages - sc",
    "sao paulo - sp",
    "sao paulo sp",
    "angra dos reis rj",
    "andira-pr",
    "novo hamburgo, rio grande do sul, brasil",
    "rio de janeiro, rio de janeiro, brasil",
    "rio de janeiro \\rio de janeiro"
])]["seller_city"].value_counts()

seller_city
sao paulo - sp                              3
lages - sc                                  1
novo hamburgo, rio grande do sul, brasil    1
rio de janeiro \rio de janeiro              1
andira-pr                                   1
sao paulo sp                                1
angra dos reis rj                           1
rio de janeiro, rio de janeiro, brasil      1
Name: count, dtype: int64

In [440]:
city_format_corrections = {
    "sao paulo - sp": "sao paulo",
    "lages - sc": "lages",
    "novo hamburgo, rio grande do sul, brasil": "novo hamburgo",
    "rio de janeiro \\rio de janeiro": "rio de janeiro",
    "andira-pr": "andira",
    "sao paulo sp": "sao paulo",
    "angra dos reis rj": "angra dos reis",
    "rio de janeiro, rio de janeiro, brasil": "rio de janeiro"
}

sellers_clean["seller_city"] = sellers_clean["seller_city"].replace(city_format_corrections)

In [441]:
sellers_clean["seller_city"].isin(city_format_corrections.keys()).sum()

np.int64(0)

### 11.7 Final Check

In [442]:
sellers_clean.duplicated().sum()

np.int64(0)

In [443]:
sellers_clean.dtypes

seller_id                 object
seller_zip_code_prefix    object
seller_city               object
seller_state              object
dtype: object

In [444]:
(sellers_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

In [445]:
sellers_clean["seller_city"].nunique()

558

### 11.8 Save Cleaned Sellers Dataset

In [446]:
sellers_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_sellers.csv", index=False)

print("Cleaned sellers dataset saved successfully!")

Cleaned sellers dataset saved successfully!

## 12. Category Translation Dataset — Cleaning & Quality Check

### 12.1 First Five Rows

In [447]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

### 12.2 Data Types

In [448]:
category_translation.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

### 12.3 Missing Values

In [449]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

### 12.4 Duplicate Rows

In [450]:
category_translation.duplicated().sum()

np.int64(0)

### 12.5 Check leading and trailing spaces

In [451]:
category_translation_clean = category_translation.copy()

In [452]:
category_translation_clean["product_category_name"].str.strip().ne(
    category_translation_clean["product_category_name"]
).sum()

np.int64(0)

In [453]:
category_translation_clean["product_category_name_english"].str.strip().ne(
    category_translation_clean["product_category_name_english"]
).sum()

np.int64(0)

### 12.6 Check whether both columns are completely lowercase

In [454]:
category_translation_clean["product_category_name"].eq(
    category_translation_clean["product_category_name"].str.lower()
).all()

np.True_

In [455]:
category_translation_clean["product_category_name_english"].eq(
    category_translation_clean["product_category_name_english"].str.lower()
).all()

np.True_

### 12.7 Check Accents

In [456]:
category_translation_clean["product_category_name"].str.normalize("NFKD").str.encode(
    "ascii", errors="ignore"
).str.decode("utf-8").nunique()

71

In [457]:
category_translation_clean["product_category_name"].nunique()

71

### 12.8 Check empty strings / whitespace-only cells

In [458]:
(category_translation_clean.astype(str).apply(lambda x: x.str.strip() == "")).sum().sum()

np.int64(0)

### 12.9 Check unique values

In [459]:
category_translation_clean["product_category_name"].unique()

array(['beleza_saude', 'informatica_acessorios', 'automotivo',
       'cama_mesa_banho', 'moveis_decoracao', 'esporte_lazer',
       'perfumaria', 'utilidades_domesticas', 'telefonia',
       'relogios_presentes', 'alimentos_bebidas', 'bebes', 'papelaria',
       'tablets_impressao_imagem', 'brinquedos', 'telefonia_fixa',
       'ferramentas_jardim', 'fashion_bolsas_e_acessorios',
       'eletroportateis', 'consoles_games', 'audio', 'fashion_calcados',
       'cool_stuff', 'malas_acessorios', 'climatizacao',
       'construcao_ferramentas_construcao',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'construcao_ferramentas_jardim', 'fashion_roupa_masculina',
       'pet_shop', 'moveis_escritorio', 'market_place', 'eletronicos',
       'eletrodomesticos', 'artigos_de_festas', 'casa_conforto',
       'construcao_ferramentas_ferramentas', 'agro_industria_e_comercio',
       'moveis_colchao_e_estofado', 'livros_tecnicos', 'casa_construcao',
       'instrumentos_musicais', 'moveis_sala',
       'construcao_ferramentas_iluminacao',
       'industria_comercio_e_negocios', 'alimentos', 'artes',
       'moveis_quarto', 'livros_interesse_geral',
       'construcao_ferramentas_seguranca',
       'fashion_underwear_e_moda_praia', 'fashion_esporte',
       'sinalizacao_e_seguranca', 'pcs', 'artigos_de_natal',
       'fashion_roupa_feminina', 'eletrodomesticos_2',
       'livros_importados', 'bebidas', 'cine_foto', 'la_cuisine',
       'musica', 'casa_conforto_2', 'portateis_casa_forno_e_cafe',
       'cds_dvds_musicais', 'dvds_blu_ray', 'flores',
       'artes_e_artesanato', 'fraldas_higiene',
       'fashion_roupa_infanto_juvenil', 'seguros_e_servicos'],
      dtype=object)

In [460]:
category_translation_clean["product_category_name_english"].unique()

array(['health_beauty', 'computers_accessories', 'auto', 'bed_bath_table',
       'furniture_decor', 'sports_leisure', 'perfumery', 'housewares',
       'telephony', 'watches_gifts', 'food_drink', 'baby', 'stationery',
       'tablets_printing_image', 'toys', 'fixed_telephony',
       'garden_tools', 'fashion_bags_accessories', 'small_appliances',
       'consoles_games', 'audio', 'fashion_shoes', 'cool_stuff',
       'luggage_accessories', 'air_conditioning',
       'construction_tools_construction',
       'kitchen_dining_laundry_garden_furniture',
       'costruction_tools_garden', 'fashion_male_clothing', 'pet_shop',
       'office_furniture', 'market_place', 'electronics',
       'home_appliances', 'party_supplies', 'home_confort',
       'costruction_tools_tools', 'agro_industry_and_commerce',
       'furniture_mattress_and_upholstery', 'books_technical',
       'home_construction', 'musical_instruments',
       'furniture_living_room', 'construction_tools_lights',
       'industry_commerce_and_business', 'food', 'art',
       'furniture_bedroom', 'books_general_interest',
       'construction_tools_safety', 'fashion_underwear_beach',
       'fashion_sport', 'signaling_and_security', 'computers',
       'christmas_supplies', 'fashio_female_clothing',
       'home_appliances_2', 'books_imported', 'drinks', 'cine_photo',
       'la_cuisine', 'music', 'home_comfort_2',
       'small_appliances_home_oven_and_coffee', 'cds_dvds_musicals',
       'dvds_blu_ray', 'flowers', 'arts_and_craftmanship',
       'diapers_and_hygiene', 'fashion_childrens_clothes',
       'security_and_services'], dtype=object)

In [461]:
category_translation_clean["product_category_name_english"].nunique()

71

### 12.10 Save the Cleaned Category Translation Dataset

In [462]:
category_translation_clean.to_csv(r"C:\Users\hafsa\OneDrive\Documents\Olist_E-Commerce_Data_Analysis\data\cleaned\clean_category_translation.csv", index=False)

print("Cleaned category translation dataset saved successfully!")

Cleaned category translation dataset saved successfully!